/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ModelRouteImport } from './routes/model'
import { Route as GetInvolvedIndexRouteImport } from './routes/get-involved/index'
import { Route as GetInvolvedAltruistRouteImport } from './routes/get-involved/altruist'
import { Route as GetInvolvedArtistRouteImport } from './routes/get-involved/artist'
import { Route as GetInvolvedAthleteRouteImport } from './routes/get-involved/athlete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedIndexRoute = GetInvolvedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GetInvolvedRoute,
} as any)
const GetInvolvedAltruistRoute = GetInvolvedAltruistRouteImport.update({
  id: '/altruist',
  path: '/altruist',
  getParentRoute: () => GetInvolvedRoute,
} as any)
const GetInvolvedArtistRoute = GetInvolvedArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => GetInvolvedRoute,
} as any)
const GetInvolvedAthleteRoute = GetInvolvedAthleteRouteImport.update({
  id: '/athlete',
  path: '/athlete',
  getParentRoute: () => GetInvolvedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRouteWithChildren
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/get-involved/altruist': typeof GetInvolvedAltruistRoute
  '/get-involved/artist': typeof GetInvolvedArtistRoute
  '/get-involved/athlete': typeof GetInvolvedAthleteRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/get-involved/altruist': typeof GetInvolvedAltruistRoute
  '/get-involved/artist': typeof GetInvolvedArtistRoute
  '/get-involved/athlete': typeof GetInvolvedAthleteRoute
  '/get-involved': typeof GetInvolvedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRouteWithChildren
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/get-involved/altruist': typeof GetInvolvedAltruistRoute
  '/get-involved/artist': typeof GetInvolvedArtistRoute
  '/get-involved/athlete': typeof GetInvolvedAthleteRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/get-involved'
    | '/leadership'
    | '/model'
    | '/get-involved/altruist'
    | '/get-involved/artist'
    | '/get-involved/athlete'
    | '/get-involved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/leadership'
    | '/model'
    | '/get-involved/altruist'
    | '/get-involved/artist'
    | '/get-involved/athlete'
    | '/get-involved'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/get-involved'
    | '/leadership'
    | '/model'
    | '/get-involved/altruist'
    | '/get-involved/artist'
    | '/get-involved/athlete'
    | '/get-involved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRouteWithChildren
  LeadershipRoute: typeof LeadershipRoute
  ModelRoute: typeof ModelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/': {
      id: '/get-involved/'
      path: '/'
      fullPath: '/get-involved/'
      preLoaderRoute: typeof GetInvolvedIndexRouteImport
      parentRoute: typeof GetInvolvedRoute
    }
    '/get-involved/altruist': {
      id: '/get-involved/altruist'
      path: '/altruist'
      fullPath: '/get-involved/altruist'
      preLoaderRoute: typeof GetInvolvedAltruistRouteImport
      parentRoute: typeof GetInvolvedRoute
    }
    '/get-involved/artist': {
      id: '/get-involved/artist'
      path: '/artist'
      fullPath: '/get-involved/artist'
      preLoaderRoute: typeof GetInvolvedArtistRouteImport
      parentRoute: typeof GetInvolvedRoute
    }
    '/get-involved/athlete': {
      id: '/get-involved/athlete'
      path: '/athlete'
      fullPath: '/get-involved/athlete'
      preLoaderRoute: typeof GetInvolvedAthleteRouteImport
      parentRoute: typeof GetInvolvedRoute
    }
  }
}

interface GetInvolvedRouteChildren {
  GetInvolvedAltruistRoute: typeof GetInvolvedAltruistRoute
  GetInvolvedArtistRoute: typeof GetInvolvedArtistRoute
  GetInvolvedAthleteRoute: typeof GetInvolvedAthleteRoute
  GetInvolvedIndexRoute: typeof GetInvolvedIndexRoute
}

const GetInvolvedRouteChildren: GetInvolvedRouteChildren = {
  GetInvolvedAltruistRoute: GetInvolvedAltruistRoute,
  GetInvolvedArtistRoute: GetInvolvedArtistRoute,
  GetInvolvedAthleteRoute: GetInvolvedAthleteRoute,
  GetInvolvedIndexRoute: GetInvolvedIndexRoute,
}

const GetInvolvedRouteWithChildren = GetInvolvedRoute._addFileChildren(
  GetInvolvedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRouteWithChildren,
  LeadershipRoute: LeadershipRoute,
  ModelRoute: ModelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
